export type SearchRoutes =
  | 'Recherche'
  | 'Filtres_avances'
  | 'Sa_taille'
  | 'Sa_morphologie'
  | 'Origine_ethnique'
  | 'Niveau_etude'
  | 'Metier'
  | 'Religion'
  | 'Signe_astro'
  | 'Orientation_politique'
  | 'Tabac'
  | 'Alcool'
  | 'Pratique_sportive'
  | 'Enfants'
  | 'Revenus'
  | 'Search_pulse';
